package modelo;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;

@Entity
public class Itinerario implements Serializable {

    @OneToOne(targetEntity = Estado.class)
    private Estado origemEstado;

    @OneToOne(targetEntity = Cidade.class)
    private Cidade origemCidade;

    @Basic
    private float KmTotal;

    @OneToOne(targetEntity = Cidade.class)
    private Cidade destinoCidade;

    @Basic
    private String origem;

    @OneToOne(targetEntity = Estado.class)
    private Estado destinoEstado;

    @Id
    private Long id;

    public Itinerario() {

    }

    public Estado getOrigemEstado() {
        return this.origemEstado;
    }

    public void setOrigemEstado(Estado origemEstado) {
        this.origemEstado = origemEstado;
    }

    public Cidade getOrigemCidade() {
        return this.origemCidade;
    }

    public void setOrigemCidade(Cidade origemCidade) {
        this.origemCidade = origemCidade;
    }

    public float getKmTotal() {
        return this.KmTotal;
    }

    public void setKmTotal(float KmTotal) {
        this.KmTotal = KmTotal;
    }

    public Cidade getDestinoCidade() {
        return this.destinoCidade;
    }

    public void setDestinoCidade(Cidade destinoCidade) {
        this.destinoCidade = destinoCidade;
    }

    public String getOrigem() {
        return this.origem;
    }

    public void setOrigem(String origem) {
        this.origem = origem;
    }

    public Estado getDestinoEstado() {
        return this.destinoEstado;
    }

    public void setDestinoEstado(Estado destinoEstado) {
        this.destinoEstado = destinoEstado;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}
