package modelo;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

@Entity
public class Pedido implements Serializable {

    @OneToOne(targetEntity = Cliente.class)
    private Cliente cliente;

    @Basic
    private float valorTotal;

    @Basic
    private String caucao;

    @Id
    private Long id;

    @OneToMany(targetEntity = Locacao.class)
    private List<Locacao> locacoes;

    @Basic
    private String status;

    public Pedido() {

    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public float getValorTotal() {
        return this.valorTotal;
    }

    public void setValorTotal(float valorTotal) {
        this.valorTotal = valorTotal;
    }

    public String getCaucao() {
        return this.caucao;
    }

    public void setCaucao(String caucao) {
        this.caucao = caucao;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public List<Locacao> getLocacoes() {
        return this.locacoes;
    }

    public void setLocacoes(List<Locacao> locacoes) {
        this.locacoes = locacoes;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
